apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: database-image:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: db_username
            - name: POSTGRES_PASSWORD
              value: db_password
